name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
      - name: Create environment file
        run: |
          touch .env
          echo "${PYTHONPATH}"
          echo PYTHONPATH="${PYTHONPATH};home/runner/work/PortfolioManager/PortfolioManager/source" >> .env
      - name: Run tests with pytest
        run: |
          pytest --cov=source --cov-report=xml tests/ > portfolio_cov.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./portfolio_cov.xml